/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApprovalWorkflow: typeof import('./src/components/Common/ApprovalWorkflow.vue')['default']
    Breadcrumbs: typeof import('./src/components/Common/Breadcrumbs.vue')['default']
    DataTable: typeof import('./src/components/Common/DataTable.vue')['default']
    DynamicForm: typeof import('./src/components/Common/DynamicForm.vue')['default']
    FileUploader: typeof import('./src/components/Common/FileUploader.vue')['default']
    FilterBuilder: typeof import('./src/components/Common/FilterBuilder.vue')['default']
    GanttChart: typeof import('./src/components/Common/GanttChart.vue')['default']
    RiskHeatMap: typeof import('./src/components/Common/RiskHeatMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
